/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 07 10:20:56 KST 2017
 */

package org.prevayler.demos.scalability.jdbc;

import static org.evosuite.runtime.EvoAssertions.assertThrownBy;
import static org.junit.Assert.fail;

import java.sql.Connection;
import java.sql.SQLException;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true, separateClassLoader = true, useJEE = true)
public class JDBCScalabilityConnection_ESTest4 extends JDBCScalabilityConnection_ESTest_scaffolding4 {

  @Test
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try { 
        JDBCScalabilityConnection.dealWithSQLException((SQLException) null, "X&Y\"X=");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.prevayler.demos.scalability.jdbc.JDBCScalabilityConnection", e);
      }
  }

  @Test
  public void test1()  throws Throwable  {
      SQLException sQLException0 = new SQLException("IX~*iz", "IX~*iz");
      // Undeclared exception!
      try { 
        JDBCScalabilityConnection.dealWithSQLException(sQLException0, "IX~*iz");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // SQLException IX~*iz.
         //
         assertThrownBy("org.prevayler.demos.scalability.jdbc.JDBCScalabilityConnection", e);
      }
  }

}
